### ISSUE TITLE
Wrong date on the recent discoveries

### ISSUE THREAD

**Issue by k94ll13nn3** [daveaglick/discoverdotnet#149]
Hi,

First, thanks for this awesome site 👍!

The last 3 recent discoveries all have the same date (June 2, 2018). I amready noticed it yesterday but it was only the last 2 recent discoveries (the date was June 1, 2018).

**Comment by daveaglick** [comment]
Well that's really strange. The data is right, and they're correct in the feeds so might be a Vue or moment.js problem.

**Comment by daveaglick** [comment]
Good catch, turns out non-project discoveries weren't getting their dates set in the JSON for the home page.
