### ISSUE TITLE
Reappearing content every day

### ISSUE THREAD

**Issue by hasan-hasanov** [daveaglick/discoverdotnet#216]
I have noticed several times that the content **Unable to add 'Global.asax' to the Web site. An unknown WinINet error has occurred (code 12113).** is shown every day. I believe it is because of its date which is _Monday, January 1, 0001 at 12:00 AM_. You can see it from [here](https://www.swoo.co.uk/blog/post/29/unable-to-add-'globalasax'-to-the-web-site-an-unknown-wininet-error-has-occurred-code-12113). I think it gets posted every day on midnight.

**Comment by daveaglick** [comment]
Where is this shown? Discover is a static site built by Wyam and uploaded to Netlify via their API. There’s no Visual Studio or other build tooling involved that uses a Global.asax file. Are you seeing this as a blog post? If so, can you tell from which blog?

**Comment by hasan-hasanov** [comment]
I am seeing it every day on https://discoverdot.net/. I already gave a link to the blog post [https://www.swoo.co.uk/blog/post/29/unable-to-add-'globalasax'-to-the-web-site-an-unknown-wininet-error-has-occurred-code-12113](https://www.swoo.co.uk/blog/post/29/unable-to-add-'globalasax'-to-the-web-site-an-unknown-wininet-error-has-occurred-code-12113) . Even now it is shown as recently published.

**Comment by daveaglick** [comment]
Ah, I see. This is from @woodss blog. The Discover site just aggregates whatever it gets via the RSS feeds. In this case, it appears Steve’s blog is actually publishing a post with that title (I.e., this isn’t an error but an actual post):

![e7cc243f-0258-40f0-9597-745ae3a03ff3](https://user-images.githubusercontent.com/1020407/43614379-40b4cb56-9681-11e8-8df3-e1b246e5ea83.png)

So I guess the question is: why is the post showing up repeatedly? I don’t see more than one copy on the Discover page for that blog, nor do I see duplicates in the RSS feed for that blog. Perhaps the blog is republishing that post every day and moving it to the top?

Any thoughts @woodss? When was that post originally written?

**Comment by woodss** [comment]
Sorry about that guys - somehow the timestamp got corrupted and was indeed 01/01/0001 00:00:00 which caused it to get changed to the current date + time every time the RSS feed was refreshed. 

I've deleted the offending post so it won't appear again.

**Comment by daveaglick** [comment]
Thanks @woodss! It’s been interesting the way running this site has served a little like a validation for blogs and other feeds. Yours isn’t the first feed problem I’ve caught from here :)
