### ISSUE TITLE
Blogs as OPML import

### ISSUE THREAD

**Issue by SeanKilleen** [daveaglick/discoverdotnet#289]
I don't say it nearly enough, but I reference this project a *ton* -- thank you @daveaglick!

I had an idea and if you're up for it, let me know and I can submit a PR.

You have a number of great blog resources that I'd love to periodically bring into my Feedly account, which allows the import of OPML. Any objection to me adding the generation of an OPML file and optionally a link to the file itself for download? 

If you're OK with the idea, let me know where you'd like to the file to reside and where (if anywhere) you'd like me to add a link to it on the site, and I'll submit the PR. (if no preferences, let me know and I can take a first pass at it based on my instincts).

**Comment by daveaglick** [comment]
This is a _great_ idea! I also live by Feedly and just subscribed to the aggregated feed - producing and then periodically importing an OPML is a much better idea.

First thought on location is to put it at something like `/feeds.opml` but don’t feel strongly about it - feel free to put it somewhere else if it seems more appropriate. I’d like to link to it wherever we can - under the news area on the homepage, on the blogs and broadcasts pages, etc.
