### ISSUE TITLE
Project should use IExecutionContext.CreateHttpClient() instead of creating clients directly

### ISSUE THREAD

**Issue by SeanKilleen** [daveaglick/discoverdotnet#309]
Leaving this as a note for myself. Now that the site is on Wyam `v2.2.4`, instead of `var httpClient = new HttpClient()`, we can use `var httpClient = executionContext.CreateHttpClient()` to help centralize the use of `HttpClient`.

Probably an `up-for-grabs` task but I'll try to knock it out quickly when I'm able.

**Comment by daveaglick** [comment]
Beat you to it earlier today when I was merging everything in :)

**Comment by SeanKilleen** [comment]
Well I stand corrected then! 😆
