### ISSUE TITLE
Old blog post always appears first.

### ISSUE THREAD

**Issue by hasan-hasanov** [daveaglick/discoverdotnet#356]
Hello,

I am one of the daily readers of Discover.NET and for some time it came to my attention that @RickStrahl's post always comes in first in the newsfeed.

Here I provide an image that demonstrates the problem:

![Untitled](https://user-images.githubusercontent.com/18668078/76214535-9a40e180-6215-11ea-87ed-84c4fff8b52e.png)

**Comment by daveaglick** [comment]
That’s really interesting. Good for Rick :). I’ll try to take a look today and see what’s going on, though I can guess one of the RSS update vs. published date might be incorrect in the feed (i.e., future dated) so I probably need to account for that situation.
