### ISSUE TITLE
Is discoverdotnet still works?

### ISSUE THREAD

**Issue by hasan-hasanov** [daveaglick/discoverdotnet#362]
Over the years discoverdotnet became mine and a lot of my colleagues primary news source.
There is not a single new post for almost 2 weeks.
It seems to be the issue is with discoverdotnet since there are new blog posts for example in hanselminutes or vs magazine or .NET Foundation for example.

So my question is is discoverdotnet still works?

**Comment by daveaglick** [comment]
Yikes! I absolutely still works (or is supposed to anyway). Obviously there's a problem, thanks for bringing it to my attention. I've been _extremely_ distracted recently so didn't even notice. I'll try to get this resolved ASAP.

**Comment by daveaglick** [comment]
It’s back, thanks for the report! Please don’t hesitate to let me know if you see it’s not updating again.

**Comment by hasan-hasanov** [comment]
Thank you very much for the fast response!
