### ISSUE TITLE
Discoverdotnet not updating again :(

### ISSUE THREAD

**Issue by hasan-hasanov** [daveaglick/discoverdotnet#388]
Can you please check it Dave?

**Comment by daveaglick** [comment]
Thanks for the head's up (again). This is getting old. The issue appears to be that Azure DevOps just stops triggering the scheduled build job. It worked fine for months and now appears to be halting every couple weeks so I suspect an earlier "bug" in DevOps where the tenant would time out after a few days if nothing happened in the repo has resurfaced.

Pretty sure it's time to look at moving off of DevOps entirely and onto GitHub Actions. I'll take a look at that as soon as I have a little extended hacking time for Discover .NET. In the meantime I've kicked it and a build is going now.
