### ISSUE TITLE
When using RSS feed in Feedly formatting of article abstract is incorrect

### ISSUE THREAD

**Issue by TechWatching** [daveaglick/discoverdotnet#431]
I am using Feedly as my RSS feed reader and have been following discoverdot.net RSS feed for a quite a bit. However lately I noticed that the article abstracts of discoverdot.net does not display correctly anymore.

Example of what I see:
![image](https://user-images.githubusercontent.com/15186176/104844868-dc758d80-58d2-11eb-8ce7-725a84c63373.png)

All other RSS feeds are correctly displayed. Could you tell me if the issue come from discoverdot.net or feedly ? Maybe something has changed and is now encoded althought it was not before or maybe it's something that changed in Feedly but right now I cannot tell for sure. I have tested with another feed reader (flowreader.com) though and I had the same issue.

Thanks in advance.

**Comment by daveaglick** [comment]
Thanks for the heads up! That definitely looks like it's on my end, some sort of double-encoding of the HTML perhaps. I'll look into it.

**Comment by daveaglick** [comment]
Yeah, this was definitely my fault - think I've figured it out (I broke it when porting to Statiq a little while ago) and the feeds should be fixed in the next build (every two hours or so). Thanks again for alerting me!
