### ISSUE TITLE
Question: non-English content

### ISSUE THREAD

**Issue by darkl** [daveaglick/discoverdotnet#58]
Hi!

Nice work!

I wanted to ask you what is your opinion on non-English material. For instance, I wrote nearly 400 posts about dot net tips in Hebrew (located [here](http://elad.zelingher.com/tips)).

Would it be ok to add this as a resource (it is not very active as a blog)?

Elad

**Comment by daveaglick** [comment]
I think adding it as a resource is an excellent idea. That strikes a good balance between having a single language for things like the projects and recent news, but not excluding valuable resources like this.

Let’s add it as a resource with an English description so most visitors will know what it is (and then also maybe repeated in Hebrew). If enough foreign language resources come in, perhaps I can even add a language filter to the resources page.

**Comment by daveaglick** [comment]
Submitted as PR #62
