### ISSUE TITLE
Blog page is white

### ISSUE THREAD

**Issue by laurentkempe** [daveaglick/discoverdotnet#67]
When I navigate to my blog link https://discoverdot.net/blogs/laurentkempe I see a white page!

btw @daveaglick Thanks for including my blog on your site 👍

**Comment by daveaglick** [comment]
Funny, I just noticed another one with the same problem: https://discoverdot.net/blogs/mattwarren

It's picking up the RSS feed because I can see the most recent post on the card. Probably some sort of template issue with certain content. I'll take a look.
