### ISSUE TITLE
Nake project is displaying a white page.

### ISSUE THREAD

**Issue by AntiTcb** [daveaglick/discoverdotnet#73]
https://discoverdot.net/projects/nake
May be loosely related to #67, but seems less likely since that issue was closed with a recent commit.

**Comment by daveaglick** [comment]
Thanks for reporting this. I've narrowed it down to something in the readme. Hopefully I'll have a fix available shortly.

**Comment by daveaglick** [comment]
Turns out this was related to #67. In both cases, Vue was trying to parse `{{` syntax that appeared in external content. Should get fixed in the next site build within a couple hours.
