### ISSUE TITLE
Add forms for data submission

### ISSUE THREAD

**Issue by daveaglick** [daveaglick/discoverdotnet#8]
Either use something like staticman.net or pre-populate a GitHub PR from form data.

**Comment by daveaglick** [comment]
Done

**Comment by daveaglick** [comment]
One other thing we could do is pre-populate the file name based on the title or other fields. That should cut it down to a single GitHub submission click if the default fork/branch is accepted.

**Comment by StephenCleary** [comment]
That's a good idea. [slugify](https://github.com/simov/slugify) may be useful there.
